version: "3.9"
services:
  mia:
    image: mia
    volumes:
      - .:/mia
    stdin_open: true
    tty: true
    user: $UID:$GID
    entrypoint: python main.py
    working_dir: /mia/mia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
