version: "3.9"
services:
  mia:
    image: mia
    volumes:
      - .:/mia
    stdin_open: true
    tty: true
    user: $UID:$GID
    entrypoint: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
