---
name: Example Configuration
seed: 1234

actions:
  trainTarget: no
  testTarget: no
  trainAttack: yes
  testAttack: yes
  generateAttackData: no

attackModel:
  name: attack_311022_best_run
  hyperparameters:
    epochs: 1000
    batchSize: 20
    learningRate: 0.0001

targetModel:
  name: test
  type: kaggle
  classes: 100
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 0.001

attackDataset:
  name: attack_kaggle
  split: 0.8

targetDataset:
  name: kaggle
  trainSize: 10000
  testSize: 10000
  shuffle: True

...
