---
name: Example Configuration
seed: 1234

actions:
  generateShadowData: no

attackModel:
  hyperparameters:
    epochs: 50
    batchSize: 4 
    learningRate: 1e-2

attackDataset:
  name: placeholder
  split: 0.8

targetModel:
  classes: 100
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 1e-3

targetDataset:
  name: kaggle
  trainSize: 10000
  testSize: 10000
  shuffle: True

shadowDataset:
  size: 10
  method: noisy
  noisy:
    hyperparameters:
      fraction: 0.1
  hill_climbing:
    hyperparameters:
      k_max: 128
      k_min: 4
      conf_min: 0.05
      rej_max: 10
      iter_max: 300
      batchSize: 100

...
