---
name: Example Configuration
seed: 1234

actions:
  trainTarget: no
  testTarget: no
  trainAttack: yes
  testAttack: no
  generateAttackData: no

attackModel:
  name: placeholder
  hyperparameters:
    epochs: 50
    batchSize: 4 
    learningRate: 1e-2

targetModel:
  name: lr_1e-3_bs_100_epochs_200_trainsize_10000
  classes: 100
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 1e-3

attackDataset:
  name: placeholder
  split: 0.8

shadowData:
  hyperparameters:
    k_max: 128
    k_min: 4
    conf_min: 0.2
    rej_max: 10
    iter_max: 500

targetDataset:
  name: kaggle
  trainSize: 10000
  testSize: 10000
  shuffle: True

...
