---
name: Example Configuration
seed: 1234
verbose: yes

attackModel:
  hyperparameters:
    epochs: 50
    batchSize: 4 
    learningRate: 1e-2

attackDataset:
  name: placeholder
  split: 0.8 # how to split the attack dataset for testing/training
  balance: yes # wether or not the attack data should contain equal in/out records per class

targetModel:
  classes: 100 # must match dataset dimensionality
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 1e-3

targetDataset:
  name: kaggle # kaggle, kaggle_2, kaggle_10, kaggle_20, kaggle_50
  trainSize: 10000
  testSize: 10000

shadowModels:
  number: 20
  split: 0.8

shadowDataset:
  size: 10000 # set of each shadow model's training set size
  method: original # hill_climbing, noisy, original, statistic
  noisy:
    hyperparameters:
      fraction: 0.1 # amount of noise
  hill_climbing:
    hyperparameters: # as described in the paper
      k_max: 128
      k_min: 4
      conf_min: 0.2
      rej_max: 10
      iter_max: 200
      batchSize: 100
  statistic:
    hyperparameters:
  original:
    hyperparameters:

...
