---
name: Example Configuration
seed: 1234
verbose: yes

attackModel:
  hyperparameters:
    epochs: 50
    batchSize: 4 
    learningRate: 1e-2

attackDataset:
  name: placeholder
  split: 0.8
  balance: yes

targetModel:
  classes: 100
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 1e-3

targetDataset:
  name: kaggle # kaggle, kaggle_2, kaggle_10, kaggle_20, kaggle_50
  trainSize: 10000
  testSize: 10000

shadowModels:
  number: 10
  split: 0.5

shadowDataset:
  size: 30000
  # methods: hill_climbing, noisy, original, statistic
  method: statistic
  noisy:
    hyperparameters:
      fraction: 0.1
  hill_climbing:
    hyperparameters:
      k_max: 128
      k_min: 4
      conf_min: 0.05
      rej_max: 10
      iter_max: 200
      batchSize: 100
  statistic:
    hyperparameters:
  original:
    hyperparameters:

...
