---
name: Example Configuration
seed: 1234

actions:
  trainTarget: no
  testTarget: no
  trainAttack: yes
  testAttack: yes

attackModel:
  name: test

targetModel:
  name: test
  type: kaggle
  classes: 100
  hyperparameters:
    epochs: 3
    batchSize: 100
    learningRate: 0.001

attackDataset:
  name: attack_kaggle
  split: 0.8
  generate: no

targetDataset:
  name: kaggle
  trainSize: 80000
  testSize: 80000

...
