---
name: Example Configuration
seed: 1234

actions:
  trainTarget: no
  testTarget: no
  trainAttack: no
  testAttack: no
  generateShadowData: no


attackModel:
  name: placeholder
  hyperparameters:
    epochs: 50
    batchSize: 4 
    learningRate: 1e-2

targetModel:
  name: lr_1e-3_bs_100_epochs_100_trainsize_10000
  classes: 100
  hyperparameters:
    epochs: 200
    batchSize: 100
    learningRate: 1e-3

attackDataset:
  name: placeholder
  split: 0.8

shadowDataset:
  name: placeholder
  size: 100000
  method: noisy
  noisy:
    hyperparameters:
      fraction: 0.1
  hill_climbing:
    hyperparameters:
      k_max: 128
      k_min: 4
      conf_min: 0.05
      rej_max: 10
      iter_max: 300
      batchSize: 100

targetDataset:
  name: kaggle
  trainSize: 10000
  testSize: 10000
  shuffle: True

...
